package com.coconet.ifms.dao;


import org.mybatis.spring.annotation.MapperScan;

import com.coconet.ifms.vo.HktAdminUser;
import com.coconet.ifms.vo.HktAdminUserWithBLOBs;

public interface HktAdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_admin_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_admin_user
     *
     * @mbg.generated
     */
    int insert(HktAdminUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_admin_user
     *
     * @mbg.generated
     */
    int insertSelective(HktAdminUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_admin_user
     *
     * @mbg.generated
     */
    HktAdminUserWithBLOBs selectByPrimaryKey(Short userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_admin_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktAdminUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_admin_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(HktAdminUserWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_admin_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktAdminUser record);
    HktAdminUser selectByUsernameAndPassword(HktAdminUser record);
}