package com.coconet.ifms.dao;



import com.coconet.ifms.vo.HktArticle;

public interface HktArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_article
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_article
     *
     * @mbg.generated
     */
    int insert(HktArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_article
     *
     * @mbg.generated
     */
    int insertSelective(HktArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_article
     *
     * @mbg.generated
     */
    HktArticle selectByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(HktArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktArticle record);
}