package com.coconet.ifms.dao;


import com.coconet.ifms.vo.HktArticleCat;

public interface HktArticleCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_article_cat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_article_cat
     *
     * @mbg.generated
     */
    int insert(HktArticleCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_article_cat
     *
     * @mbg.generated
     */
    int insertSelective(HktArticleCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_article_cat
     *
     * @mbg.generated
     */
    HktArticleCat selectByPrimaryKey(Short catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_article_cat
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktArticleCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_article_cat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktArticleCat record);
}