package com.coconet.ifms.dao;



import com.coconet.ifms.vo.HktBrand;

public interface HktBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_brand
     *
     * @mbg.generated
     */
    int insert(HktBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_brand
     *
     * @mbg.generated
     */
    int insertSelective(HktBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_brand
     *
     * @mbg.generated
     */
    HktBrand selectByPrimaryKey(Short brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(HktBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktBrand record);
}