package com.coconet.ifms.dao;



import com.coconet.ifms.vo.HktBookingGoods;

public interface HktBookingGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_booking_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_booking_goods
     *
     * @mbg.generated
     */
    int insert(HktBookingGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_booking_goods
     *
     * @mbg.generated
     */
    int insertSelective(HktBookingGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_booking_goods
     *
     * @mbg.generated
     */
    HktBookingGoods selectByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_booking_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktBookingGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_booking_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktBookingGoods record);
}