package com.coconet.ifms.dao;



import com.coconet.ifms.vo.HktComment;

public interface HktCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_comment
     *
     * @mbg.generated
     */
    int insert(HktComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_comment
     *
     * @mbg.generated
     */
    int insertSelective(HktComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_comment
     *
     * @mbg.generated
     */
    HktComment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(HktComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktComment record);
}