package com.coconet.ifms.dao;



import com.coconet.ifms.vo.HktCollectGoods;

public interface HktCollectGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_collect_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_collect_goods
     *
     * @mbg.generated
     */
    int insert(HktCollectGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_collect_goods
     *
     * @mbg.generated
     */
    int insertSelective(HktCollectGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_collect_goods
     *
     * @mbg.generated
     */
    HktCollectGoods selectByPrimaryKey(Integer recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_collect_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktCollectGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_collect_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktCollectGoods record);
}