package com.coconet.ifms.dao;



import com.coconet.ifms.vo.HktGoodsArticleKey;

public interface HktGoodsArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_article
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(HktGoodsArticleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_article
     *
     * @mbg.generated
     */
    int insert(HktGoodsArticleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_article
     *
     * @mbg.generated
     */
    int insertSelective(HktGoodsArticleKey record);
}