package com.coconet.ifms.dao;



import java.util.List;
import java.util.Map;

import com.coconet.ifms.vo.HktGoods;
import com.coconet.ifms.vo.HktGoodsWithBLOBs;

public interface HktGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods
     *
     * @mbg.generated
     */
    int insert(HktGoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods
     *
     * @mbg.generated
     */
    int insertSelective(HktGoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods
     *
     * @mbg.generated
     */
    HktGoodsWithBLOBs selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktGoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(HktGoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktGoods record);
    
    List<HktGoods> selectByCondition(Map<String, Object> map);
   int  countByCondition(Map<String, Object> map);
}