package com.coconet.ifms.dao;



import com.coconet.ifms.vo.HktGoodsAttr;

public interface HktGoodsAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_attr
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer goodsAttrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_attr
     *
     * @mbg.generated
     */
    int insert(HktGoodsAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_attr
     *
     * @mbg.generated
     */
    int insertSelective(HktGoodsAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_attr
     *
     * @mbg.generated
     */
    HktGoodsAttr selectByPrimaryKey(Integer goodsAttrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_attr
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktGoodsAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_attr
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(HktGoodsAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_attr
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktGoodsAttr record);
}