package com.coconet.ifms.dao;



import java.util.List;

import com.coconet.ifms.vo.HktGoodsGallery;

public interface HktGoodsGalleryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_gallery
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_gallery
     *
     * @mbg.generated
     */
    int insert(HktGoodsGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_gallery
     *
     * @mbg.generated
     */
    int insertSelective(HktGoodsGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_gallery
     *
     * @mbg.generated
     */
    List<HktGoodsGallery> selectByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_gallery
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktGoodsGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_gallery
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktGoodsGallery record);
}