package com.coconet.ifms.dao;


import com.coconet.ifms.vo.HktGoodsType;

public interface HktGoodsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_type
     *
     * @mbg.generated
     */
    int insert(HktGoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_type
     *
     * @mbg.generated
     */
    int insertSelective(HktGoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_type
     *
     * @mbg.generated
     */
    HktGoodsType selectByPrimaryKey(Short catId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktGoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_goods_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktGoodsType record);
}