package com.coconet.ifms.dao;



import com.coconet.ifms.vo.HktKeywords;
import com.coconet.ifms.vo.HktKeywordsKey;

public interface HktKeywordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_keywords
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(HktKeywordsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_keywords
     *
     * @mbg.generated
     */
    int insert(HktKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_keywords
     *
     * @mbg.generated
     */
    int insertSelective(HktKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_keywords
     *
     * @mbg.generated
     */
    HktKeywords selectByPrimaryKey(HktKeywordsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_keywords
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktKeywords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_keywords
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktKeywords record);
}