package com.coconet.ifms.dao;

import java.util.List;

import com.coconet.ifms.vo.HktLm;

public interface HktLmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_lm
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_lm
     *
     * @mbg.generated
     */
    int insert(HktLm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_lm
     *
     * @mbg.generated
     */
    int insertSelective(HktLm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_lm
     *
     * @mbg.generated
     */
    HktLm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_lm
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktLm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_lm
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktLm record);
    
    List<HktLm> findAll();
    
    
}