package com.coconet.ifms.dao;



import com.coconet.ifms.vo.HktNav;

public interface HktNavMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_nav
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_nav
     *
     * @mbg.generated
     */
    int insert(HktNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_nav
     *
     * @mbg.generated
     */
    int insertSelective(HktNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_nav
     *
     * @mbg.generated
     */
    HktNav selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_nav
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_nav
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktNav record);
}