package com.coconet.ifms.dao;



import com.coconet.ifms.vo.HktRegion;

public interface HktRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_region
     *
     * @mbg.generated
     */
    int insert(HktRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_region
     *
     * @mbg.generated
     */
    int insertSelective(HktRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_region
     *
     * @mbg.generated
     */
    HktRegion selectByPrimaryKey(Short regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktRegion record);
}