package com.coconet.ifms.dao;


import com.coconet.ifms.vo.HktTemplate;

public interface HktTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_template
     *
     * @mbg.generated
     */
    int insert(HktTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_template
     *
     * @mbg.generated
     */
    int insertSelective(HktTemplate record);
}