package com.coconet.ifms.dao;


import com.coconet.ifms.vo.HktUsers;

public interface HktUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_users
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_users
     *
     * @mbg.generated
     */
    int insert(HktUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_users
     *
     * @mbg.generated
     */
    int insertSelective(HktUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_users
     *
     * @mbg.generated
     */
    HktUsers selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HktUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(HktUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hkt_users
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HktUsers record);
}