package com.coconet.ifms.vo;

public class HktAttribute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_attribute.attr_id
     *
     * @mbg.generated
     */
    private Short attrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_attribute.cat_id
     *
     * @mbg.generated
     */
    private Short catId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_attribute.attr_name
     *
     * @mbg.generated
     */
    private String attrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_attribute.attr_input_type
     *
     * @mbg.generated
     */
    private Boolean attrInputType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_attribute.attr_type
     *
     * @mbg.generated
     */
    private Boolean attrType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_attribute.attr_index
     *
     * @mbg.generated
     */
    private Boolean attrIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_attribute.sort_order
     *
     * @mbg.generated
     */
    private Byte sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_attribute.is_linked
     *
     * @mbg.generated
     */
    private Boolean isLinked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_attribute.attr_group
     *
     * @mbg.generated
     */
    private Boolean attrGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_attribute.is_show_img
     *
     * @mbg.generated
     */
    private Byte isShowImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_attribute.attr_values
     *
     * @mbg.generated
     */
    private String attrValues;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_attribute.attr_id
     *
     * @return the value of hkt_attribute.attr_id
     *
     * @mbg.generated
     */
    public Short getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_attribute.attr_id
     *
     * @param attrId the value for hkt_attribute.attr_id
     *
     * @mbg.generated
     */
    public void setAttrId(Short attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_attribute.cat_id
     *
     * @return the value of hkt_attribute.cat_id
     *
     * @mbg.generated
     */
    public Short getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_attribute.cat_id
     *
     * @param catId the value for hkt_attribute.cat_id
     *
     * @mbg.generated
     */
    public void setCatId(Short catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_attribute.attr_name
     *
     * @return the value of hkt_attribute.attr_name
     *
     * @mbg.generated
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_attribute.attr_name
     *
     * @param attrName the value for hkt_attribute.attr_name
     *
     * @mbg.generated
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName == null ? null : attrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_attribute.attr_input_type
     *
     * @return the value of hkt_attribute.attr_input_type
     *
     * @mbg.generated
     */
    public Boolean getAttrInputType() {
        return attrInputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_attribute.attr_input_type
     *
     * @param attrInputType the value for hkt_attribute.attr_input_type
     *
     * @mbg.generated
     */
    public void setAttrInputType(Boolean attrInputType) {
        this.attrInputType = attrInputType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_attribute.attr_type
     *
     * @return the value of hkt_attribute.attr_type
     *
     * @mbg.generated
     */
    public Boolean getAttrType() {
        return attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_attribute.attr_type
     *
     * @param attrType the value for hkt_attribute.attr_type
     *
     * @mbg.generated
     */
    public void setAttrType(Boolean attrType) {
        this.attrType = attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_attribute.attr_index
     *
     * @return the value of hkt_attribute.attr_index
     *
     * @mbg.generated
     */
    public Boolean getAttrIndex() {
        return attrIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_attribute.attr_index
     *
     * @param attrIndex the value for hkt_attribute.attr_index
     *
     * @mbg.generated
     */
    public void setAttrIndex(Boolean attrIndex) {
        this.attrIndex = attrIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_attribute.sort_order
     *
     * @return the value of hkt_attribute.sort_order
     *
     * @mbg.generated
     */
    public Byte getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_attribute.sort_order
     *
     * @param sortOrder the value for hkt_attribute.sort_order
     *
     * @mbg.generated
     */
    public void setSortOrder(Byte sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_attribute.is_linked
     *
     * @return the value of hkt_attribute.is_linked
     *
     * @mbg.generated
     */
    public Boolean getIsLinked() {
        return isLinked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_attribute.is_linked
     *
     * @param isLinked the value for hkt_attribute.is_linked
     *
     * @mbg.generated
     */
    public void setIsLinked(Boolean isLinked) {
        this.isLinked = isLinked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_attribute.attr_group
     *
     * @return the value of hkt_attribute.attr_group
     *
     * @mbg.generated
     */
    public Boolean getAttrGroup() {
        return attrGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_attribute.attr_group
     *
     * @param attrGroup the value for hkt_attribute.attr_group
     *
     * @mbg.generated
     */
    public void setAttrGroup(Boolean attrGroup) {
        this.attrGroup = attrGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_attribute.is_show_img
     *
     * @return the value of hkt_attribute.is_show_img
     *
     * @mbg.generated
     */
    public Byte getIsShowImg() {
        return isShowImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_attribute.is_show_img
     *
     * @param isShowImg the value for hkt_attribute.is_show_img
     *
     * @mbg.generated
     */
    public void setIsShowImg(Byte isShowImg) {
        this.isShowImg = isShowImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_attribute.attr_values
     *
     * @return the value of hkt_attribute.attr_values
     *
     * @mbg.generated
     */
    public String getAttrValues() {
        return attrValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_attribute.attr_values
     *
     * @param attrValues the value for hkt_attribute.attr_values
     *
     * @mbg.generated
     */
    public void setAttrValues(String attrValues) {
        this.attrValues = attrValues == null ? null : attrValues.trim();
    }
}