package com.coconet.ifms.vo;

public class HktBrand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_brand.brand_id
     *
     * @mbg.generated
     */
    private Short brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_brand.brand_name
     *
     * @mbg.generated
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_brand.brand_logo
     *
     * @mbg.generated
     */
    private String brandLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_brand.site_url
     *
     * @mbg.generated
     */
    private String siteUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_brand.sort_order
     *
     * @mbg.generated
     */
    private Byte sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_brand.is_show
     *
     * @mbg.generated
     */
    private Boolean isShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_brand.brand_desc
     *
     * @mbg.generated
     */
    private String brandDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_brand.brand_id
     *
     * @return the value of hkt_brand.brand_id
     *
     * @mbg.generated
     */
    public Short getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_brand.brand_id
     *
     * @param brandId the value for hkt_brand.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Short brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_brand.brand_name
     *
     * @return the value of hkt_brand.brand_name
     *
     * @mbg.generated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_brand.brand_name
     *
     * @param brandName the value for hkt_brand.brand_name
     *
     * @mbg.generated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_brand.brand_logo
     *
     * @return the value of hkt_brand.brand_logo
     *
     * @mbg.generated
     */
    public String getBrandLogo() {
        return brandLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_brand.brand_logo
     *
     * @param brandLogo the value for hkt_brand.brand_logo
     *
     * @mbg.generated
     */
    public void setBrandLogo(String brandLogo) {
        this.brandLogo = brandLogo == null ? null : brandLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_brand.site_url
     *
     * @return the value of hkt_brand.site_url
     *
     * @mbg.generated
     */
    public String getSiteUrl() {
        return siteUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_brand.site_url
     *
     * @param siteUrl the value for hkt_brand.site_url
     *
     * @mbg.generated
     */
    public void setSiteUrl(String siteUrl) {
        this.siteUrl = siteUrl == null ? null : siteUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_brand.sort_order
     *
     * @return the value of hkt_brand.sort_order
     *
     * @mbg.generated
     */
    public Byte getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_brand.sort_order
     *
     * @param sortOrder the value for hkt_brand.sort_order
     *
     * @mbg.generated
     */
    public void setSortOrder(Byte sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_brand.is_show
     *
     * @return the value of hkt_brand.is_show
     *
     * @mbg.generated
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_brand.is_show
     *
     * @param isShow the value for hkt_brand.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_brand.brand_desc
     *
     * @return the value of hkt_brand.brand_desc
     *
     * @mbg.generated
     */
    public String getBrandDesc() {
        return brandDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_brand.brand_desc
     *
     * @param brandDesc the value for hkt_brand.brand_desc
     *
     * @mbg.generated
     */
    public void setBrandDesc(String brandDesc) {
        this.brandDesc = brandDesc == null ? null : brandDesc.trim();
    }
}