package com.coconet.ifms.vo;

public class HktCollectGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_collect_goods.rec_id
     *
     * @mbg.generated
     */
    private Integer recId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_collect_goods.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_collect_goods.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_collect_goods.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_collect_goods.is_attention
     *
     * @mbg.generated
     */
    private Boolean isAttention;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_collect_goods.rec_id
     *
     * @return the value of hkt_collect_goods.rec_id
     *
     * @mbg.generated
     */
    public Integer getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_collect_goods.rec_id
     *
     * @param recId the value for hkt_collect_goods.rec_id
     *
     * @mbg.generated
     */
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_collect_goods.user_id
     *
     * @return the value of hkt_collect_goods.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_collect_goods.user_id
     *
     * @param userId the value for hkt_collect_goods.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_collect_goods.goods_id
     *
     * @return the value of hkt_collect_goods.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_collect_goods.goods_id
     *
     * @param goodsId the value for hkt_collect_goods.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_collect_goods.add_time
     *
     * @return the value of hkt_collect_goods.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_collect_goods.add_time
     *
     * @param addTime the value for hkt_collect_goods.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_collect_goods.is_attention
     *
     * @return the value of hkt_collect_goods.is_attention
     *
     * @mbg.generated
     */
    public Boolean getIsAttention() {
        return isAttention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_collect_goods.is_attention
     *
     * @param isAttention the value for hkt_collect_goods.is_attention
     *
     * @mbg.generated
     */
    public void setIsAttention(Boolean isAttention) {
        this.isAttention = isAttention;
    }
}