package com.coconet.ifms.vo;

public class HktCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.cat_id
     *
     * @mbg.generated
     */
    private Short catId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.cat_name
     *
     * @mbg.generated
     */
    private String catName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.cat_desc
     *
     * @mbg.generated
     */
    private String catDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.parent_id
     *
     * @mbg.generated
     */
    private Short parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.sort_order
     *
     * @mbg.generated
     */
    private Boolean sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.template_file
     *
     * @mbg.generated
     */
    private String templateFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.measure_unit
     *
     * @mbg.generated
     */
    private String measureUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.show_in_nav
     *
     * @mbg.generated
     */
    private Boolean showInNav;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.style
     *
     * @mbg.generated
     */
    private String style;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.is_show
     *
     * @mbg.generated
     */
    private Boolean isShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.grade
     *
     * @mbg.generated
     */
    private Byte grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.filter_attr
     *
     * @mbg.generated
     */
    private String filterAttr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.is_top_style
     *
     * @mbg.generated
     */
    private Integer isTopStyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.is_top_show
     *
     * @mbg.generated
     */
    private Integer isTopShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_category.show_parent_id
     *
     * @mbg.generated
     */
    private Short showParentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.cat_id
     *
     * @return the value of hkt_category.cat_id
     *
     * @mbg.generated
     */
    public Short getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.cat_id
     *
     * @param catId the value for hkt_category.cat_id
     *
     * @mbg.generated
     */
    public void setCatId(Short catId) {
        this.catId = catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.cat_name
     *
     * @return the value of hkt_category.cat_name
     *
     * @mbg.generated
     */
    public String getCatName() {
        return catName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.cat_name
     *
     * @param catName the value for hkt_category.cat_name
     *
     * @mbg.generated
     */
    public void setCatName(String catName) {
        this.catName = catName == null ? null : catName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.keywords
     *
     * @return the value of hkt_category.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.keywords
     *
     * @param keywords the value for hkt_category.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.cat_desc
     *
     * @return the value of hkt_category.cat_desc
     *
     * @mbg.generated
     */
    public String getCatDesc() {
        return catDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.cat_desc
     *
     * @param catDesc the value for hkt_category.cat_desc
     *
     * @mbg.generated
     */
    public void setCatDesc(String catDesc) {
        this.catDesc = catDesc == null ? null : catDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.parent_id
     *
     * @return the value of hkt_category.parent_id
     *
     * @mbg.generated
     */
    public Short getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.parent_id
     *
     * @param parentId the value for hkt_category.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Short parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.sort_order
     *
     * @return the value of hkt_category.sort_order
     *
     * @mbg.generated
     */
    public Boolean getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.sort_order
     *
     * @param sortOrder the value for hkt_category.sort_order
     *
     * @mbg.generated
     */
    public void setSortOrder(Boolean sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.template_file
     *
     * @return the value of hkt_category.template_file
     *
     * @mbg.generated
     */
    public String getTemplateFile() {
        return templateFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.template_file
     *
     * @param templateFile the value for hkt_category.template_file
     *
     * @mbg.generated
     */
    public void setTemplateFile(String templateFile) {
        this.templateFile = templateFile == null ? null : templateFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.measure_unit
     *
     * @return the value of hkt_category.measure_unit
     *
     * @mbg.generated
     */
    public String getMeasureUnit() {
        return measureUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.measure_unit
     *
     * @param measureUnit the value for hkt_category.measure_unit
     *
     * @mbg.generated
     */
    public void setMeasureUnit(String measureUnit) {
        this.measureUnit = measureUnit == null ? null : measureUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.show_in_nav
     *
     * @return the value of hkt_category.show_in_nav
     *
     * @mbg.generated
     */
    public Boolean getShowInNav() {
        return showInNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.show_in_nav
     *
     * @param showInNav the value for hkt_category.show_in_nav
     *
     * @mbg.generated
     */
    public void setShowInNav(Boolean showInNav) {
        this.showInNav = showInNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.style
     *
     * @return the value of hkt_category.style
     *
     * @mbg.generated
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.style
     *
     * @param style the value for hkt_category.style
     *
     * @mbg.generated
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.is_show
     *
     * @return the value of hkt_category.is_show
     *
     * @mbg.generated
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.is_show
     *
     * @param isShow the value for hkt_category.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.grade
     *
     * @return the value of hkt_category.grade
     *
     * @mbg.generated
     */
    public Byte getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.grade
     *
     * @param grade the value for hkt_category.grade
     *
     * @mbg.generated
     */
    public void setGrade(Byte grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.filter_attr
     *
     * @return the value of hkt_category.filter_attr
     *
     * @mbg.generated
     */
    public String getFilterAttr() {
        return filterAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.filter_attr
     *
     * @param filterAttr the value for hkt_category.filter_attr
     *
     * @mbg.generated
     */
    public void setFilterAttr(String filterAttr) {
        this.filterAttr = filterAttr == null ? null : filterAttr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.is_top_style
     *
     * @return the value of hkt_category.is_top_style
     *
     * @mbg.generated
     */
    public Integer getIsTopStyle() {
        return isTopStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.is_top_style
     *
     * @param isTopStyle the value for hkt_category.is_top_style
     *
     * @mbg.generated
     */
    public void setIsTopStyle(Integer isTopStyle) {
        this.isTopStyle = isTopStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.is_top_show
     *
     * @return the value of hkt_category.is_top_show
     *
     * @mbg.generated
     */
    public Integer getIsTopShow() {
        return isTopShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.is_top_show
     *
     * @param isTopShow the value for hkt_category.is_top_show
     *
     * @mbg.generated
     */
    public void setIsTopShow(Integer isTopShow) {
        this.isTopShow = isTopShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_category.show_parent_id
     *
     * @return the value of hkt_category.show_parent_id
     *
     * @mbg.generated
     */
    public Short getShowParentId() {
        return showParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_category.show_parent_id
     *
     * @param showParentId the value for hkt_category.show_parent_id
     *
     * @mbg.generated
     */
    public void setShowParentId(Short showParentId) {
        this.showParentId = showParentId;
    }
}