package com.coconet.ifms.vo;

public class HktComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_comment.comment_id
     *
     * @mbg.generated
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_comment.comment_type
     *
     * @mbg.generated
     */
    private Byte commentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_comment.id_value
     *
     * @mbg.generated
     */
    private Integer idValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_comment.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_comment.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_comment.comment_rank
     *
     * @mbg.generated
     */
    private Boolean commentRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_comment.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_comment.ip_address
     *
     * @mbg.generated
     */
    private String ipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_comment.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_comment.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_comment.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_comment.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_comment.comment_id
     *
     * @return the value of hkt_comment.comment_id
     *
     * @mbg.generated
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_comment.comment_id
     *
     * @param commentId the value for hkt_comment.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_comment.comment_type
     *
     * @return the value of hkt_comment.comment_type
     *
     * @mbg.generated
     */
    public Byte getCommentType() {
        return commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_comment.comment_type
     *
     * @param commentType the value for hkt_comment.comment_type
     *
     * @mbg.generated
     */
    public void setCommentType(Byte commentType) {
        this.commentType = commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_comment.id_value
     *
     * @return the value of hkt_comment.id_value
     *
     * @mbg.generated
     */
    public Integer getIdValue() {
        return idValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_comment.id_value
     *
     * @param idValue the value for hkt_comment.id_value
     *
     * @mbg.generated
     */
    public void setIdValue(Integer idValue) {
        this.idValue = idValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_comment.email
     *
     * @return the value of hkt_comment.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_comment.email
     *
     * @param email the value for hkt_comment.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_comment.user_name
     *
     * @return the value of hkt_comment.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_comment.user_name
     *
     * @param userName the value for hkt_comment.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_comment.comment_rank
     *
     * @return the value of hkt_comment.comment_rank
     *
     * @mbg.generated
     */
    public Boolean getCommentRank() {
        return commentRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_comment.comment_rank
     *
     * @param commentRank the value for hkt_comment.comment_rank
     *
     * @mbg.generated
     */
    public void setCommentRank(Boolean commentRank) {
        this.commentRank = commentRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_comment.add_time
     *
     * @return the value of hkt_comment.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_comment.add_time
     *
     * @param addTime the value for hkt_comment.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_comment.ip_address
     *
     * @return the value of hkt_comment.ip_address
     *
     * @mbg.generated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_comment.ip_address
     *
     * @param ipAddress the value for hkt_comment.ip_address
     *
     * @mbg.generated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_comment.status
     *
     * @return the value of hkt_comment.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_comment.status
     *
     * @param status the value for hkt_comment.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_comment.parent_id
     *
     * @return the value of hkt_comment.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_comment.parent_id
     *
     * @param parentId the value for hkt_comment.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_comment.user_id
     *
     * @return the value of hkt_comment.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_comment.user_id
     *
     * @param userId the value for hkt_comment.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_comment.content
     *
     * @return the value of hkt_comment.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_comment.content
     *
     * @param content the value for hkt_comment.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}