package com.coconet.ifms.vo;

public class HktGoodsWithBLOBs extends HktGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods.goods_desc
     *
     * @mbg.generated
     */
    private String goodsDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods.goods_shipai
     *
     * @mbg.generated
     */
    private String goodsShipai;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods.goods_desc
     *
     * @return the value of hkt_goods.goods_desc
     *
     * @mbg.generated
     */
    public String getGoodsDesc() {
        return goodsDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods.goods_desc
     *
     * @param goodsDesc the value for hkt_goods.goods_desc
     *
     * @mbg.generated
     */
    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc == null ? null : goodsDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods.goods_shipai
     *
     * @return the value of hkt_goods.goods_shipai
     *
     * @mbg.generated
     */
    public String getGoodsShipai() {
        return goodsShipai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods.goods_shipai
     *
     * @param goodsShipai the value for hkt_goods.goods_shipai
     *
     * @mbg.generated
     */
    public void setGoodsShipai(String goodsShipai) {
        this.goodsShipai = goodsShipai == null ? null : goodsShipai.trim();
    }
}