package com.coconet.ifms.vo;

public class HktGoodsGallery {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_gallery.img_id
     *
     * @mbg.generated
     */
    private Integer imgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_gallery.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_gallery.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_gallery.img_desc
     *
     * @mbg.generated
     */
    private String imgDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_gallery.thumb_url
     *
     * @mbg.generated
     */
    private String thumbUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_gallery.img_original
     *
     * @mbg.generated
     */
    private String imgOriginal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_gallery.order
     *
     * @mbg.generated
     */
    private Integer order;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_gallery.img_id
     *
     * @return the value of hkt_goods_gallery.img_id
     *
     * @mbg.generated
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_gallery.img_id
     *
     * @param imgId the value for hkt_goods_gallery.img_id
     *
     * @mbg.generated
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_gallery.goods_id
     *
     * @return the value of hkt_goods_gallery.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_gallery.goods_id
     *
     * @param goodsId the value for hkt_goods_gallery.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_gallery.img_url
     *
     * @return the value of hkt_goods_gallery.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_gallery.img_url
     *
     * @param imgUrl the value for hkt_goods_gallery.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_gallery.img_desc
     *
     * @return the value of hkt_goods_gallery.img_desc
     *
     * @mbg.generated
     */
    public String getImgDesc() {
        return imgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_gallery.img_desc
     *
     * @param imgDesc the value for hkt_goods_gallery.img_desc
     *
     * @mbg.generated
     */
    public void setImgDesc(String imgDesc) {
        this.imgDesc = imgDesc == null ? null : imgDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_gallery.thumb_url
     *
     * @return the value of hkt_goods_gallery.thumb_url
     *
     * @mbg.generated
     */
    public String getThumbUrl() {
        return thumbUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_gallery.thumb_url
     *
     * @param thumbUrl the value for hkt_goods_gallery.thumb_url
     *
     * @mbg.generated
     */
    public void setThumbUrl(String thumbUrl) {
        this.thumbUrl = thumbUrl == null ? null : thumbUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_gallery.img_original
     *
     * @return the value of hkt_goods_gallery.img_original
     *
     * @mbg.generated
     */
    public String getImgOriginal() {
        return imgOriginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_gallery.img_original
     *
     * @param imgOriginal the value for hkt_goods_gallery.img_original
     *
     * @mbg.generated
     */
    public void setImgOriginal(String imgOriginal) {
        this.imgOriginal = imgOriginal == null ? null : imgOriginal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_gallery.order
     *
     * @return the value of hkt_goods_gallery.order
     *
     * @mbg.generated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_gallery.order
     *
     * @param order the value for hkt_goods_gallery.order
     *
     * @mbg.generated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }
}