package com.coconet.ifms.vo;

public class HktGoodsAttr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_attr.goods_attr_id
     *
     * @mbg.generated
     */
    private Integer goodsAttrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_attr.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_attr.attr_id
     *
     * @mbg.generated
     */
    private Short attrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_attr.attr_price
     *
     * @mbg.generated
     */
    private String attrPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_attr.img_id
     *
     * @mbg.generated
     */
    private Integer imgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_attr.linked_attr
     *
     * @mbg.generated
     */
    private String linkedAttr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_attr.attr_value
     *
     * @mbg.generated
     */
    private String attrValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_attr.goods_attr_id
     *
     * @return the value of hkt_goods_attr.goods_attr_id
     *
     * @mbg.generated
     */
    public Integer getGoodsAttrId() {
        return goodsAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_attr.goods_attr_id
     *
     * @param goodsAttrId the value for hkt_goods_attr.goods_attr_id
     *
     * @mbg.generated
     */
    public void setGoodsAttrId(Integer goodsAttrId) {
        this.goodsAttrId = goodsAttrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_attr.goods_id
     *
     * @return the value of hkt_goods_attr.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_attr.goods_id
     *
     * @param goodsId the value for hkt_goods_attr.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_attr.attr_id
     *
     * @return the value of hkt_goods_attr.attr_id
     *
     * @mbg.generated
     */
    public Short getAttrId() {
        return attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_attr.attr_id
     *
     * @param attrId the value for hkt_goods_attr.attr_id
     *
     * @mbg.generated
     */
    public void setAttrId(Short attrId) {
        this.attrId = attrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_attr.attr_price
     *
     * @return the value of hkt_goods_attr.attr_price
     *
     * @mbg.generated
     */
    public String getAttrPrice() {
        return attrPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_attr.attr_price
     *
     * @param attrPrice the value for hkt_goods_attr.attr_price
     *
     * @mbg.generated
     */
    public void setAttrPrice(String attrPrice) {
        this.attrPrice = attrPrice == null ? null : attrPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_attr.img_id
     *
     * @return the value of hkt_goods_attr.img_id
     *
     * @mbg.generated
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_attr.img_id
     *
     * @param imgId the value for hkt_goods_attr.img_id
     *
     * @mbg.generated
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_attr.linked_attr
     *
     * @return the value of hkt_goods_attr.linked_attr
     *
     * @mbg.generated
     */
    public String getLinkedAttr() {
        return linkedAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_attr.linked_attr
     *
     * @param linkedAttr the value for hkt_goods_attr.linked_attr
     *
     * @mbg.generated
     */
    public void setLinkedAttr(String linkedAttr) {
        this.linkedAttr = linkedAttr == null ? null : linkedAttr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_attr.attr_value
     *
     * @return the value of hkt_goods_attr.attr_value
     *
     * @mbg.generated
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_attr.attr_value
     *
     * @param attrValue the value for hkt_goods_attr.attr_value
     *
     * @mbg.generated
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue == null ? null : attrValue.trim();
    }
}