package com.coconet.ifms.vo;

public class HktGoodsArticleKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_article.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_article.article_id
     *
     * @mbg.generated
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_goods_article.admin_id
     *
     * @mbg.generated
     */
    private Byte adminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_article.goods_id
     *
     * @return the value of hkt_goods_article.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_article.goods_id
     *
     * @param goodsId the value for hkt_goods_article.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_article.article_id
     *
     * @return the value of hkt_goods_article.article_id
     *
     * @mbg.generated
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_article.article_id
     *
     * @param articleId the value for hkt_goods_article.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_goods_article.admin_id
     *
     * @return the value of hkt_goods_article.admin_id
     *
     * @mbg.generated
     */
    public Byte getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_goods_article.admin_id
     *
     * @param adminId the value for hkt_goods_article.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Byte adminId) {
        this.adminId = adminId;
    }
}