package com.coconet.ifms.vo;

public class HktKeywords extends HktKeywordsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_keywords.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_keywords.count
     *
     * @return the value of hkt_keywords.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_keywords.count
     *
     * @param count the value for hkt_keywords.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}