package com.coconet.ifms.vo;

public class HktLmmx {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_lmmx.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_lmmx.lmid
     *
     * @mbg.generated
     */
    private Integer lmid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_lmmx.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_lmmx.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_lmmx.sx
     *
     * @mbg.generated
     */
    private Integer sx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_lmmx.is_show
     *
     * @mbg.generated
     */
    private Byte isShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_lmmx.id
     *
     * @return the value of hkt_lmmx.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_lmmx.id
     *
     * @param id the value for hkt_lmmx.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_lmmx.lmid
     *
     * @return the value of hkt_lmmx.lmid
     *
     * @mbg.generated
     */
    public Integer getLmid() {
        return lmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_lmmx.lmid
     *
     * @param lmid the value for hkt_lmmx.lmid
     *
     * @mbg.generated
     */
    public void setLmid(Integer lmid) {
        this.lmid = lmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_lmmx.type
     *
     * @return the value of hkt_lmmx.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_lmmx.type
     *
     * @param type the value for hkt_lmmx.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_lmmx.value
     *
     * @return the value of hkt_lmmx.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_lmmx.value
     *
     * @param value the value for hkt_lmmx.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_lmmx.sx
     *
     * @return the value of hkt_lmmx.sx
     *
     * @mbg.generated
     */
    public Integer getSx() {
        return sx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_lmmx.sx
     *
     * @param sx the value for hkt_lmmx.sx
     *
     * @mbg.generated
     */
    public void setSx(Integer sx) {
        this.sx = sx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_lmmx.is_show
     *
     * @return the value of hkt_lmmx.is_show
     *
     * @mbg.generated
     */
    public Byte getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_lmmx.is_show
     *
     * @param isShow the value for hkt_lmmx.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(Byte isShow) {
        this.isShow = isShow;
    }
}