package com.coconet.ifms.vo;

public class HktLm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_lm.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_lm.titletype
     *
     * @mbg.generated
     */
    private Boolean titletype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_lm.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_lm.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_lm.intro
     *
     * @mbg.generated
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_lm.sx
     *
     * @mbg.generated
     */
    private Integer sx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_lm.is_show
     *
     * @mbg.generated
     */
    private Byte isShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_lm.title_show
     *
     * @mbg.generated
     */
    private Byte titleShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_lm.id
     *
     * @return the value of hkt_lm.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_lm.id
     *
     * @param id the value for hkt_lm.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_lm.titletype
     *
     * @return the value of hkt_lm.titletype
     *
     * @mbg.generated
     */
    public Boolean getTitletype() {
        return titletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_lm.titletype
     *
     * @param titletype the value for hkt_lm.titletype
     *
     * @mbg.generated
     */
    public void setTitletype(Boolean titletype) {
        this.titletype = titletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_lm.url
     *
     * @return the value of hkt_lm.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_lm.url
     *
     * @param url the value for hkt_lm.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_lm.name
     *
     * @return the value of hkt_lm.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_lm.name
     *
     * @param name the value for hkt_lm.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_lm.intro
     *
     * @return the value of hkt_lm.intro
     *
     * @mbg.generated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_lm.intro
     *
     * @param intro the value for hkt_lm.intro
     *
     * @mbg.generated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_lm.sx
     *
     * @return the value of hkt_lm.sx
     *
     * @mbg.generated
     */
    public Integer getSx() {
        return sx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_lm.sx
     *
     * @param sx the value for hkt_lm.sx
     *
     * @mbg.generated
     */
    public void setSx(Integer sx) {
        this.sx = sx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_lm.is_show
     *
     * @return the value of hkt_lm.is_show
     *
     * @mbg.generated
     */
    public Byte getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_lm.is_show
     *
     * @param isShow the value for hkt_lm.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(Byte isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_lm.title_show
     *
     * @return the value of hkt_lm.title_show
     *
     * @mbg.generated
     */
    public Byte getTitleShow() {
        return titleShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_lm.title_show
     *
     * @param titleShow the value for hkt_lm.title_show
     *
     * @mbg.generated
     */
    public void setTitleShow(Byte titleShow) {
        this.titleShow = titleShow;
    }
}