package com.coconet.ifms.vo;

public class HktNav {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_nav.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_nav.ctype
     *
     * @mbg.generated
     */
    private String ctype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_nav.cid
     *
     * @mbg.generated
     */
    private Short cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_nav.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_nav.ifshow
     *
     * @mbg.generated
     */
    private Boolean ifshow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_nav.vieworder
     *
     * @mbg.generated
     */
    private Boolean vieworder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_nav.opennew
     *
     * @mbg.generated
     */
    private Boolean opennew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_nav.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_nav.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_nav.id
     *
     * @return the value of hkt_nav.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_nav.id
     *
     * @param id the value for hkt_nav.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_nav.ctype
     *
     * @return the value of hkt_nav.ctype
     *
     * @mbg.generated
     */
    public String getCtype() {
        return ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_nav.ctype
     *
     * @param ctype the value for hkt_nav.ctype
     *
     * @mbg.generated
     */
    public void setCtype(String ctype) {
        this.ctype = ctype == null ? null : ctype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_nav.cid
     *
     * @return the value of hkt_nav.cid
     *
     * @mbg.generated
     */
    public Short getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_nav.cid
     *
     * @param cid the value for hkt_nav.cid
     *
     * @mbg.generated
     */
    public void setCid(Short cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_nav.name
     *
     * @return the value of hkt_nav.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_nav.name
     *
     * @param name the value for hkt_nav.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_nav.ifshow
     *
     * @return the value of hkt_nav.ifshow
     *
     * @mbg.generated
     */
    public Boolean getIfshow() {
        return ifshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_nav.ifshow
     *
     * @param ifshow the value for hkt_nav.ifshow
     *
     * @mbg.generated
     */
    public void setIfshow(Boolean ifshow) {
        this.ifshow = ifshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_nav.vieworder
     *
     * @return the value of hkt_nav.vieworder
     *
     * @mbg.generated
     */
    public Boolean getVieworder() {
        return vieworder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_nav.vieworder
     *
     * @param vieworder the value for hkt_nav.vieworder
     *
     * @mbg.generated
     */
    public void setVieworder(Boolean vieworder) {
        this.vieworder = vieworder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_nav.opennew
     *
     * @return the value of hkt_nav.opennew
     *
     * @mbg.generated
     */
    public Boolean getOpennew() {
        return opennew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_nav.opennew
     *
     * @param opennew the value for hkt_nav.opennew
     *
     * @mbg.generated
     */
    public void setOpennew(Boolean opennew) {
        this.opennew = opennew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_nav.url
     *
     * @return the value of hkt_nav.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_nav.url
     *
     * @param url the value for hkt_nav.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_nav.type
     *
     * @return the value of hkt_nav.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_nav.type
     *
     * @param type the value for hkt_nav.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}