package com.coconet.ifms.vo;

public class HktRegion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_region.region_id
     *
     * @mbg.generated
     */
    private Short regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_region.parent_id
     *
     * @mbg.generated
     */
    private Short parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_region.region_name
     *
     * @mbg.generated
     */
    private String regionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_region.region_type
     *
     * @mbg.generated
     */
    private Boolean regionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_region.agency_id
     *
     * @mbg.generated
     */
    private Short agencyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_region.region_id
     *
     * @return the value of hkt_region.region_id
     *
     * @mbg.generated
     */
    public Short getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_region.region_id
     *
     * @param regionId the value for hkt_region.region_id
     *
     * @mbg.generated
     */
    public void setRegionId(Short regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_region.parent_id
     *
     * @return the value of hkt_region.parent_id
     *
     * @mbg.generated
     */
    public Short getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_region.parent_id
     *
     * @param parentId the value for hkt_region.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Short parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_region.region_name
     *
     * @return the value of hkt_region.region_name
     *
     * @mbg.generated
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_region.region_name
     *
     * @param regionName the value for hkt_region.region_name
     *
     * @mbg.generated
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_region.region_type
     *
     * @return the value of hkt_region.region_type
     *
     * @mbg.generated
     */
    public Boolean getRegionType() {
        return regionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_region.region_type
     *
     * @param regionType the value for hkt_region.region_type
     *
     * @mbg.generated
     */
    public void setRegionType(Boolean regionType) {
        this.regionType = regionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_region.agency_id
     *
     * @return the value of hkt_region.agency_id
     *
     * @mbg.generated
     */
    public Short getAgencyId() {
        return agencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_region.agency_id
     *
     * @param agencyId the value for hkt_region.agency_id
     *
     * @mbg.generated
     */
    public void setAgencyId(Short agencyId) {
        this.agencyId = agencyId;
    }
}