package com.coconet.ifms.vo;

public class HktTemplate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_template.filename
     *
     * @mbg.generated
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_template.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_template.library
     *
     * @mbg.generated
     */
    private String library;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_template.sort_order
     *
     * @mbg.generated
     */
    private Boolean sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_template.id
     *
     * @mbg.generated
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_template.number
     *
     * @mbg.generated
     */
    private Boolean number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_template.type
     *
     * @mbg.generated
     */
    private Boolean type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_template.theme
     *
     * @mbg.generated
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_template.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_template.filename
     *
     * @return the value of hkt_template.filename
     *
     * @mbg.generated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_template.filename
     *
     * @param filename the value for hkt_template.filename
     *
     * @mbg.generated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_template.region
     *
     * @return the value of hkt_template.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_template.region
     *
     * @param region the value for hkt_template.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_template.library
     *
     * @return the value of hkt_template.library
     *
     * @mbg.generated
     */
    public String getLibrary() {
        return library;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_template.library
     *
     * @param library the value for hkt_template.library
     *
     * @mbg.generated
     */
    public void setLibrary(String library) {
        this.library = library == null ? null : library.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_template.sort_order
     *
     * @return the value of hkt_template.sort_order
     *
     * @mbg.generated
     */
    public Boolean getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_template.sort_order
     *
     * @param sortOrder the value for hkt_template.sort_order
     *
     * @mbg.generated
     */
    public void setSortOrder(Boolean sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_template.id
     *
     * @return the value of hkt_template.id
     *
     * @mbg.generated
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_template.id
     *
     * @param id the value for hkt_template.id
     *
     * @mbg.generated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_template.number
     *
     * @return the value of hkt_template.number
     *
     * @mbg.generated
     */
    public Boolean getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_template.number
     *
     * @param number the value for hkt_template.number
     *
     * @mbg.generated
     */
    public void setNumber(Boolean number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_template.type
     *
     * @return the value of hkt_template.type
     *
     * @mbg.generated
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_template.type
     *
     * @param type the value for hkt_template.type
     *
     * @mbg.generated
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_template.theme
     *
     * @return the value of hkt_template.theme
     *
     * @mbg.generated
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_template.theme
     *
     * @param theme the value for hkt_template.theme
     *
     * @mbg.generated
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_template.remarks
     *
     * @return the value of hkt_template.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_template.remarks
     *
     * @param remarks the value for hkt_template.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}