package com.coconet.ifms.vo;

public class HktTuijiandian {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_tuijiandian.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_tuijiandian.dian_name
     *
     * @mbg.generated
     */
    private String dianName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_tuijiandian.dis_order
     *
     * @mbg.generated
     */
    private Byte disOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_tuijiandian.display
     *
     * @mbg.generated
     */
    private Boolean display;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_tuijiandian.is_del
     *
     * @mbg.generated
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_tuijiandian.id
     *
     * @return the value of hkt_tuijiandian.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_tuijiandian.id
     *
     * @param id the value for hkt_tuijiandian.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_tuijiandian.dian_name
     *
     * @return the value of hkt_tuijiandian.dian_name
     *
     * @mbg.generated
     */
    public String getDianName() {
        return dianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_tuijiandian.dian_name
     *
     * @param dianName the value for hkt_tuijiandian.dian_name
     *
     * @mbg.generated
     */
    public void setDianName(String dianName) {
        this.dianName = dianName == null ? null : dianName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_tuijiandian.dis_order
     *
     * @return the value of hkt_tuijiandian.dis_order
     *
     * @mbg.generated
     */
    public Byte getDisOrder() {
        return disOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_tuijiandian.dis_order
     *
     * @param disOrder the value for hkt_tuijiandian.dis_order
     *
     * @mbg.generated
     */
    public void setDisOrder(Byte disOrder) {
        this.disOrder = disOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_tuijiandian.display
     *
     * @return the value of hkt_tuijiandian.display
     *
     * @mbg.generated
     */
    public Boolean getDisplay() {
        return display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_tuijiandian.display
     *
     * @param display the value for hkt_tuijiandian.display
     *
     * @mbg.generated
     */
    public void setDisplay(Boolean display) {
        this.display = display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_tuijiandian.is_del
     *
     * @return the value of hkt_tuijiandian.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_tuijiandian.is_del
     *
     * @param isDel the value for hkt_tuijiandian.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}