package com.coconet.ifms.vo;

import java.math.BigDecimal;
import java.util.Date;

public class HktUsers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.question
     *
     * @mbg.generated
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.answer
     *
     * @mbg.generated
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.sex
     *
     * @mbg.generated
     */
    private Boolean sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.user_money
     *
     * @mbg.generated
     */
    private BigDecimal userMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.frozen_money
     *
     * @mbg.generated
     */
    private BigDecimal frozenMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.pay_points
     *
     * @mbg.generated
     */
    private Integer payPoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.rank_points
     *
     * @mbg.generated
     */
    private Integer rankPoints;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.address_id
     *
     * @mbg.generated
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.reg_time
     *
     * @mbg.generated
     */
    private Integer regTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.last_login
     *
     * @mbg.generated
     */
    private Integer lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.last_time
     *
     * @mbg.generated
     */
    private Date lastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.last_ip
     *
     * @mbg.generated
     */
    private String lastIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.visit_count
     *
     * @mbg.generated
     */
    private Short visitCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.user_rank
     *
     * @mbg.generated
     */
    private Byte userRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.is_special
     *
     * @mbg.generated
     */
    private Byte isSpecial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.ec_salt
     *
     * @mbg.generated
     */
    private String ecSalt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.salt
     *
     * @mbg.generated
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.flag
     *
     * @mbg.generated
     */
    private Byte flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.alias
     *
     * @mbg.generated
     */
    private String alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.msn
     *
     * @mbg.generated
     */
    private String msn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.office_phone
     *
     * @mbg.generated
     */
    private String officePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.home_phone
     *
     * @mbg.generated
     */
    private String homePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.mobile_phone
     *
     * @mbg.generated
     */
    private String mobilePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.is_validated
     *
     * @mbg.generated
     */
    private Byte isValidated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.credit_line
     *
     * @mbg.generated
     */
    private BigDecimal creditLine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.passwd_question
     *
     * @mbg.generated
     */
    private String passwdQuestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.passwd_answer
     *
     * @mbg.generated
     */
    private String passwdAnswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hkt_users.aite_id
     *
     * @mbg.generated
     */
    private String aiteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.user_id
     *
     * @return the value of hkt_users.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.user_id
     *
     * @param userId the value for hkt_users.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.email
     *
     * @return the value of hkt_users.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.email
     *
     * @param email the value for hkt_users.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.user_name
     *
     * @return the value of hkt_users.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.user_name
     *
     * @param userName the value for hkt_users.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.password
     *
     * @return the value of hkt_users.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.password
     *
     * @param password the value for hkt_users.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.question
     *
     * @return the value of hkt_users.question
     *
     * @mbg.generated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.question
     *
     * @param question the value for hkt_users.question
     *
     * @mbg.generated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.answer
     *
     * @return the value of hkt_users.answer
     *
     * @mbg.generated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.answer
     *
     * @param answer the value for hkt_users.answer
     *
     * @mbg.generated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.sex
     *
     * @return the value of hkt_users.sex
     *
     * @mbg.generated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.sex
     *
     * @param sex the value for hkt_users.sex
     *
     * @mbg.generated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.birthday
     *
     * @return the value of hkt_users.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.birthday
     *
     * @param birthday the value for hkt_users.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.user_money
     *
     * @return the value of hkt_users.user_money
     *
     * @mbg.generated
     */
    public BigDecimal getUserMoney() {
        return userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.user_money
     *
     * @param userMoney the value for hkt_users.user_money
     *
     * @mbg.generated
     */
    public void setUserMoney(BigDecimal userMoney) {
        this.userMoney = userMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.frozen_money
     *
     * @return the value of hkt_users.frozen_money
     *
     * @mbg.generated
     */
    public BigDecimal getFrozenMoney() {
        return frozenMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.frozen_money
     *
     * @param frozenMoney the value for hkt_users.frozen_money
     *
     * @mbg.generated
     */
    public void setFrozenMoney(BigDecimal frozenMoney) {
        this.frozenMoney = frozenMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.pay_points
     *
     * @return the value of hkt_users.pay_points
     *
     * @mbg.generated
     */
    public Integer getPayPoints() {
        return payPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.pay_points
     *
     * @param payPoints the value for hkt_users.pay_points
     *
     * @mbg.generated
     */
    public void setPayPoints(Integer payPoints) {
        this.payPoints = payPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.rank_points
     *
     * @return the value of hkt_users.rank_points
     *
     * @mbg.generated
     */
    public Integer getRankPoints() {
        return rankPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.rank_points
     *
     * @param rankPoints the value for hkt_users.rank_points
     *
     * @mbg.generated
     */
    public void setRankPoints(Integer rankPoints) {
        this.rankPoints = rankPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.address_id
     *
     * @return the value of hkt_users.address_id
     *
     * @mbg.generated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.address_id
     *
     * @param addressId the value for hkt_users.address_id
     *
     * @mbg.generated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.reg_time
     *
     * @return the value of hkt_users.reg_time
     *
     * @mbg.generated
     */
    public Integer getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.reg_time
     *
     * @param regTime the value for hkt_users.reg_time
     *
     * @mbg.generated
     */
    public void setRegTime(Integer regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.last_login
     *
     * @return the value of hkt_users.last_login
     *
     * @mbg.generated
     */
    public Integer getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.last_login
     *
     * @param lastLogin the value for hkt_users.last_login
     *
     * @mbg.generated
     */
    public void setLastLogin(Integer lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.last_time
     *
     * @return the value of hkt_users.last_time
     *
     * @mbg.generated
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.last_time
     *
     * @param lastTime the value for hkt_users.last_time
     *
     * @mbg.generated
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.last_ip
     *
     * @return the value of hkt_users.last_ip
     *
     * @mbg.generated
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.last_ip
     *
     * @param lastIp the value for hkt_users.last_ip
     *
     * @mbg.generated
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.visit_count
     *
     * @return the value of hkt_users.visit_count
     *
     * @mbg.generated
     */
    public Short getVisitCount() {
        return visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.visit_count
     *
     * @param visitCount the value for hkt_users.visit_count
     *
     * @mbg.generated
     */
    public void setVisitCount(Short visitCount) {
        this.visitCount = visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.user_rank
     *
     * @return the value of hkt_users.user_rank
     *
     * @mbg.generated
     */
    public Byte getUserRank() {
        return userRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.user_rank
     *
     * @param userRank the value for hkt_users.user_rank
     *
     * @mbg.generated
     */
    public void setUserRank(Byte userRank) {
        this.userRank = userRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.is_special
     *
     * @return the value of hkt_users.is_special
     *
     * @mbg.generated
     */
    public Byte getIsSpecial() {
        return isSpecial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.is_special
     *
     * @param isSpecial the value for hkt_users.is_special
     *
     * @mbg.generated
     */
    public void setIsSpecial(Byte isSpecial) {
        this.isSpecial = isSpecial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.ec_salt
     *
     * @return the value of hkt_users.ec_salt
     *
     * @mbg.generated
     */
    public String getEcSalt() {
        return ecSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.ec_salt
     *
     * @param ecSalt the value for hkt_users.ec_salt
     *
     * @mbg.generated
     */
    public void setEcSalt(String ecSalt) {
        this.ecSalt = ecSalt == null ? null : ecSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.salt
     *
     * @return the value of hkt_users.salt
     *
     * @mbg.generated
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.salt
     *
     * @param salt the value for hkt_users.salt
     *
     * @mbg.generated
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.parent_id
     *
     * @return the value of hkt_users.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.parent_id
     *
     * @param parentId the value for hkt_users.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.flag
     *
     * @return the value of hkt_users.flag
     *
     * @mbg.generated
     */
    public Byte getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.flag
     *
     * @param flag the value for hkt_users.flag
     *
     * @mbg.generated
     */
    public void setFlag(Byte flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.alias
     *
     * @return the value of hkt_users.alias
     *
     * @mbg.generated
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.alias
     *
     * @param alias the value for hkt_users.alias
     *
     * @mbg.generated
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.msn
     *
     * @return the value of hkt_users.msn
     *
     * @mbg.generated
     */
    public String getMsn() {
        return msn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.msn
     *
     * @param msn the value for hkt_users.msn
     *
     * @mbg.generated
     */
    public void setMsn(String msn) {
        this.msn = msn == null ? null : msn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.qq
     *
     * @return the value of hkt_users.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.qq
     *
     * @param qq the value for hkt_users.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.office_phone
     *
     * @return the value of hkt_users.office_phone
     *
     * @mbg.generated
     */
    public String getOfficePhone() {
        return officePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.office_phone
     *
     * @param officePhone the value for hkt_users.office_phone
     *
     * @mbg.generated
     */
    public void setOfficePhone(String officePhone) {
        this.officePhone = officePhone == null ? null : officePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.home_phone
     *
     * @return the value of hkt_users.home_phone
     *
     * @mbg.generated
     */
    public String getHomePhone() {
        return homePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.home_phone
     *
     * @param homePhone the value for hkt_users.home_phone
     *
     * @mbg.generated
     */
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone == null ? null : homePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.mobile_phone
     *
     * @return the value of hkt_users.mobile_phone
     *
     * @mbg.generated
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.mobile_phone
     *
     * @param mobilePhone the value for hkt_users.mobile_phone
     *
     * @mbg.generated
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone == null ? null : mobilePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.is_validated
     *
     * @return the value of hkt_users.is_validated
     *
     * @mbg.generated
     */
    public Byte getIsValidated() {
        return isValidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.is_validated
     *
     * @param isValidated the value for hkt_users.is_validated
     *
     * @mbg.generated
     */
    public void setIsValidated(Byte isValidated) {
        this.isValidated = isValidated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.credit_line
     *
     * @return the value of hkt_users.credit_line
     *
     * @mbg.generated
     */
    public BigDecimal getCreditLine() {
        return creditLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.credit_line
     *
     * @param creditLine the value for hkt_users.credit_line
     *
     * @mbg.generated
     */
    public void setCreditLine(BigDecimal creditLine) {
        this.creditLine = creditLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.passwd_question
     *
     * @return the value of hkt_users.passwd_question
     *
     * @mbg.generated
     */
    public String getPasswdQuestion() {
        return passwdQuestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.passwd_question
     *
     * @param passwdQuestion the value for hkt_users.passwd_question
     *
     * @mbg.generated
     */
    public void setPasswdQuestion(String passwdQuestion) {
        this.passwdQuestion = passwdQuestion == null ? null : passwdQuestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.passwd_answer
     *
     * @return the value of hkt_users.passwd_answer
     *
     * @mbg.generated
     */
    public String getPasswdAnswer() {
        return passwdAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.passwd_answer
     *
     * @param passwdAnswer the value for hkt_users.passwd_answer
     *
     * @mbg.generated
     */
    public void setPasswdAnswer(String passwdAnswer) {
        this.passwdAnswer = passwdAnswer == null ? null : passwdAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hkt_users.aite_id
     *
     * @return the value of hkt_users.aite_id
     *
     * @mbg.generated
     */
    public String getAiteId() {
        return aiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hkt_users.aite_id
     *
     * @param aiteId the value for hkt_users.aite_id
     *
     * @mbg.generated
     */
    public void setAiteId(String aiteId) {
        this.aiteId = aiteId == null ? null : aiteId.trim();
    }
}